grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: SVC
    module: sklearn.svm
    search_param_grid:
      kernel:
      - 'linear'
      - 'poly'
      - 'rbf'
  module_2:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
    search_param_grid:
      n_estimators:
      - 40
      - 60
      - 100
      - 125
      - 150
      criterion:
      - 'gini'
      - 'entropy'
      max_depth:
      - 2
      - 6
      - 8
      - 10
      - 12
      min_samples_leaf:
      - 2
      - 4
      - 8
      - 10
      - 12
      min_samples_split:
      - 2
      - 6
      - 8
      - 10
      - 12
  module_3:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      n_neighbors: 5
    search_param_grid:
      n_neighbors:
      - 5
      - 7
      - 9
      - 11
      - 13
      - 17
      algorithm:
      - 'auto'
      - 'ball_tree'
      - 'kd_tree'
      - 'brute'
  module_4:
    class: DecisionTreeClassifier
    module: sklearn.tree
    search_param_grid:
      max_depth:
      - 2
      - 3
      - 5
      - 10
      - 20
      min_samples_leaf:
      - 5
      - 10
      - 20
      - 50
      - 100
      - 150
      criterion:
      - 'gini'
      - 'entropy'